-- Seed data scraped from https://www.iamreal.fyi (books + races).
-- Run AFTER schema.sql. Idempotent: clears the tables first.

TRUNCATE books, races RESTART IDENTITY;

INSERT INTO books (title, author, language, status, finished_at) VALUES
  ('Doctor Jivago', 'Boris Pasternak', 'French', 'to-read', NULL),
  ('Ufred - Russland fra innsiden', 'Åsne Seierstad', 'Norwegian', 'to-read', NULL),
  ('Eremitt Krepsene', 'Anne Ragde', 'Norwegian', 'to-read', NULL),
  ('Today we die a little', 'Richard Askwith', 'English', 'to-read', NULL),
  ('Voices from Chernobyl', 'S. Alexievitch', 'French', 'to-read', NULL),
  ('L’effondrement', 'Edouard Louis', 'French', 'to-read', NULL),
  ('Landet som ble for rikt', 'Martin Bech Holte', 'Norwegian', 'to-read', NULL),
  ('La Classe de Neige', 'Emmanuel Carrère', 'French', 'to-read', NULL),
  ('The Gadfly', 'Ethel Voynich', 'English', 'to-read', NULL),
  ('Souvenirs et Correspondance', 'Vassili Grossman', 'French', 'to-read', NULL),
  ('The Anxious Generation', 'Jonathan Haidt', 'English', 'to-read', NULL),
  ('Quiet street', 'Mikhail Osorgin', 'French', 'to-read', NULL),
  ('MANIAC', 'Benjamín Labatut', 'French', 'to-read', NULL),
  ('Alternativt Statsbudsjett', 'Martin Bech Holte', 'Norwegian', 'to-read', NULL),
  ('Livonov', 'Emmanuel Carrère', 'French', 'to-read', NULL),
  ('La Fille du capitaine', 'Alexander Pushkin', 'French', 'read', make_date(2022,1,1)),
  ('Oliver Twist', 'Charles Dickens', 'English', 'read', make_date(2022,1,1)),
  ('War and Peace', 'Leo Tolstoy', 'English', 'read', make_date(2022,1,1)),
  ('Changer: méthode', 'Edouard Louis', 'French', 'read', make_date(2022,1,1)),
  ('La Peste', 'Albert Camus', 'French', 'read', make_date(2022,1,1)),
  ('La familia grande', 'Camille Kouchner', 'French', 'read', make_date(2022,1,1)),
  ('Germinal', 'Emile Zola', 'French', 'read', make_date(2022,1,1)),
  ('Je vous écris de Moscou', 'Alexandre S', 'French', 'read', make_date(2022,1,1)),
  ('Fyrsten', 'Henrik Langeland', 'Norwegian', 'read', make_date(2022,1,1)),
  ('Wonderboy', 'Henrik Langeland', 'Norwegian', 'read', make_date(2022,1,1)),
  ('Eugénie Grandet', 'Honoré de Balzac', 'French', 'read', make_date(2022,1,1)),
  ('L''Auberge rouge', 'Honoré de Balzac', 'French', 'read', make_date(2022,1,1)),
  ('Le Père Goriot', 'Honoré de Balzac', 'French', 'read', make_date(2022,1,1)),
  ('Le Domaine Pouchkine', 'Sergei Dovlatov', 'French', 'read', make_date(2022,1,1)),
  ('Le Joueur', 'Fyodor Dostoevsky', 'French', 'read', make_date(2022,1,1)),
  ('Qui a tué mon père', 'Edouard Louis', 'French', 'read', make_date(2022,1,1)),
  ('La Fin de l''homme rouge', 'Svetlana Alexievich', 'French', 'read', make_date(2022,1,1)),
  ('Derniers Témoins', 'Svetlana Alexievich', 'French', 'read', make_date(2022,1,1)),
  ('La guerre n''a pas un visage de femme', 'Svetlana Alexievich', 'French', 'read', make_date(2022,1,1)),
  ('Boys in Zink', 'Svetlana Alexievich', 'French', 'read', make_date(2023,1,1)),
  ('Permanent Record', 'Edward Snowden', 'English', 'read', make_date(2023,1,1)),
  ('Guerre', 'Louis-Ferdinand Céline', 'French', 'read', make_date(2023,1,1)),
  ('Figures du communisme', 'Frederic Lordon', 'French', 'read', make_date(2023,1,1)),
  ('Le coup du fou', 'Alessandro Barbaglia', 'French', 'read', make_date(2023,1,1)),
  ('Kolyma Tales', 'Varlam Shalamov', 'French', 'read', make_date(2023,1,1)),
  ('Petersburg’s tales', 'Nikolai Gogol', 'Norwegian', 'read', make_date(2023,1,1)),
  ('Le siège de Leningrad', 'Yury Riabinkin', 'French', 'read', make_date(2023,1,1)),
  ('Combats et métamorphoses d''une femme', 'Edouard Louis', 'French', 'read', make_date(2023,1,1)),
  ('Showtime!', 'Henrik Langeland', 'Norwegian', 'read', make_date(2023,1,1)),
  ('Les Époux Orlov', 'Maxim Gorky', 'French', 'read', make_date(2023,1,1)),
  ('Ici les aubes sont plus douces', 'Boris Vasilyev', 'French', 'read', make_date(2023,1,1)),
  ('La Russie, un nouvel échiquier', 'Jean de Gliniasty', 'French', 'read', make_date(2023,1,1)),
  ('Morphine', 'M. Boulgakov', 'English', 'read', make_date(2023,1,1)),
  ('Le Docteur Jivago 1', 'Boris Pasternak', 'Norwegian', 'read', make_date(2023,1,1)),
  ('Les Paysans', 'Honoré de Balzac', 'French', 'read', make_date(2023,1,1)),
  ('The death of Ivan Ilyich', 'Leo Tolstoy', 'English', 'read', make_date(2024,1,1)),
  ('La Peau de chagrin', 'Honoré de Balzac', 'French', 'read', make_date(2024,1,1)),
  ('Drive your plow over the bones of the dead', 'Olga Tokarczuk', 'English', 'read', make_date(2024,1,1)),
  ('Tueurs à gages', 'Jean-Michel Décugis', 'French', 'read', make_date(2024,1,1)),
  ('Les Bienveillantes', 'Jonathan Littell', 'French', 'read', make_date(2024,1,1)),
  ('The Grapes of Wrath', 'John Steinbeck', 'English', 'read', make_date(2024,1,1)),
  ('Hadji Murat', 'Leo Tolstoy', 'English', 'read', make_date(2024,1,1)),
  ('Alyosha the Pot', 'Leo Tolstoy', 'English', 'read', make_date(2024,1,1)),
  ('The Forged Coupon', 'Leo Tolstoy', 'English', 'read', make_date(2024,1,1)),
  ('After the Ball', 'Leo Tolstoy', 'English', 'read', make_date(2024,1,1)),
  ('Father Sergius', 'Leo Tolstoy', 'English', 'read', make_date(2024,1,1)),
  ('Master and Man', 'Leo Tolstoy', 'English', 'read', make_date(2024,1,1)),
  ('The Devil', 'Leo Tolstoy', 'English', 'read', make_date(2024,1,1)),
  ('The Kreutzer Sonata', 'Leo Tolstoy', 'English', 'read', make_date(2024,1,1)),
  ('The Diary of a Madman', 'Leo Tolstoy', 'English', 'read', make_date(2024,1,1)),
  ('The Prisoner of the Caucasus', 'Leo Tolstoy', 'English', 'read', make_date(2024,1,1)),
  ('Landet som lovet alt', 'Sidsel Wold', 'Norwegian', 'read', make_date(2024,1,1)),
  ('Det amerikanske paradokset', 'Hilde Eliassen Restad', 'Norwegian', 'read', make_date(2024,1,1)),
  ('Evenings on a Farm Near Dikanka', 'Nikolai Gogol', 'French', 'read', make_date(2024,1,1)),
  ('L''Obscurantisme vert', 'Yves Roucaute', NULL, 'to-read', NULL),
  ('The Overstory', 'Richard Powers', NULL, 'to-read', NULL),
  ('Le clan des seigneurs', 'Paul-Antoine Martin', NULL, 'to-read', NULL),
  ('Les Âmes mortes', 'Nikolai Gogol', NULL, 'to-read', NULL),
  ('La fabrique du crétin digital', 'Michel Desmurget', NULL, 'purchased', NULL),
  ('The Lower Depths', 'Maxim Gorky', NULL, 'purchased', NULL),
  ('La science au coeur de nos vies', 'Maurice Tubiana', NULL, 'to-read', NULL),
  ('Le mensonge', 'Leonid Andreyev', NULL, 'to-read', NULL),
  ('Géopolitique de la Russie', 'Jean de Gliniasty', NULL, 'to-read', NULL),
  ('Les Douze Chaises', 'Ilf and Petrov', NULL, 'purchased', NULL),
  ('Le Médecin de Campagne', 'Honoré de Balzac', 'French', 'to-read', NULL),
  ('La société du spectacle', 'Guy Debord', NULL, 'to-read', NULL),
  ('La guerre des métaux rares', 'Guillaume Pitron', NULL, 'to-read', NULL),
  ('Véridique rapport sur les dernières chances de sauver le capitalisme en Italie', 'Gianfranco Sanguinetti', NULL, 'to-read', NULL),
  ('Sustainable Energy - Without the hot air', 'David MacKay', NULL, 'to-read', NULL),
  ('Le Docteur Jivago 2', 'Boris Pasternak', NULL, 'purchased', NULL),
  ('Dark Double', 'Andrei Tsygankov', NULL, 'to-read', NULL),
  ('Voyage de Pétersbourg à Moscou', 'Alexander Radishchev', NULL, 'to-read', NULL),
  ('La guerre par le droit', 'Adam Baczko', NULL, 'to-read', NULL),
  ('Des larmes invisibles au', NULL, NULL, 'to-read', NULL),
  ('Demons', 'Fyodor Dostoevsky', NULL, 'to-read', NULL),
  ('L''île de Sakhaline', 'Anton Chekhov', NULL, 'to-read', NULL);

INSERT INTO races (name, race_date, distance, time, location, strava_link) VALUES
  ('Trondheim Marathon', '2025-09-06', 'Marathon', NULL, 'Trondheim', 'https://www.strava.com/activities/15714697344'),
  ('Ecotrail Oslo 80K', '2023-05-20', '80K', NULL, 'Oslo', 'https://www.strava.com/activities/9106227398'),
  ('Larvik Kyststien Trail Ultra 50K', '2022-07-16', '50K', NULL, 'Larvik', 'https://www.strava.com/activities/7477964786'),
  ('Ecotrail Oslo 50K', '2022-05-28', '50K', NULL, 'Oslo', 'https://www.strava.com/activities/7216253148'),
  ('Ultra Birken 60K', '2018-06-09', '60K', NULL, NULL, 'https://www.strava.com/activities/1627142838'),
  ('Bayeux Half Marathon', '2017-03-19', 'Half', NULL, 'Bayeux', 'https://www.strava.com/activities/906530565'),
  ('Xtrem Trail Normandie', '2016-09-11', NULL, NULL, 'Normandie', 'https://www.strava.com/activities/708179519'),
  ('Ecotrail Oslo 30K', '2016-05-21', '30K', NULL, 'Oslo', 'https://www.strava.com/activities/583221212'),
  ('Trondheim Half Marathon', '2014-09-06', 'Half', NULL, 'Trondheim', 'https://www.strava.com/activities/190536427');
